# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExpressWash' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExpressWash

	pod ‘Mapbox-iOS-SDK’, ‘~> 5.8’

	pod 'SwiftLint'
	
	pod 'Stripe'

	pod 'PaymentKit'

	pod 'IQKeyboardManagerSwift'

end
