# SwiftLint configuration file for Lambda School
#
# For any changes to this file, tag all team members in the PR for quick approval or discussion
#
# See current configuration with:
# swiftlint rules
#
# See documentation for the latest (master branch) rules at: https://github.com/realm/SwiftLint/blob/master/Rules.md
# and https://github.com/realm/SwiftLint for an example of options in this file
#
disabled_rules: # rule identifiers to exclude from running
  - class_delegate_protocol # This breaks if you have a delegate protocol that inherits from a class-bound protocol (see: SwiftyTables DataSourceDelegate)
  - identifier_name
  - redundant_objc_attribute 
  - todo
  - trailing_comma
  - vertical_parameter_alignment # does not work with tab indentation: https://github.com/realm/SwiftLint/issues/1573
  - colon
  - comma
  - control_statement
  - unavailable_function
  - weak_delegate
  - implicit_return
  - explicit_init
 
excluded: # paths to ignore during linting.
  - Carthage
  - Swift Style Guide.playground
  - fastlane/*
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

opt_in_rules:
  - anyobject_protocol
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - convenience_type
  - empty_count
  - empty_xctest_method
  - fatal_error_message
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_control_flow_label
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher

  # Experimental
  - unused_import
  - unused_private_declaration

# Rule options
conditional_returns_on_newline:
  if_only: true
file_length:
  warning: 800
  error: 1000
line_length:
  warning: 300
  error: 1000
  ignores_comments: true
  ignores_interpolated_strings: true
multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true
type_body_length:
  warning: 500
  error: 1200
vertical_whitespace:
  max_empty_lines: 2
trailing_whitespace:
  ignores_empty_lines: true
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
