exclude_patterns:
    - "tests/"
    - "spec/"
    - "**/vendor/"
    - "**/node_modules/"
    - "data/migrations"
    - "data/seeds"
engines:
    duplication:
        enabled: true
        config:
            languages:
                javascript:
                    mass_threshold: 175
checks:
    method-lines:
        config:
            threshold: 30
