const Incidents = [
  {
    src: ['https://www.youtube.com/watch?v=s7MM1VauRHo'],
    state: 'Oregon',
    city: 'Portland',
    desc:
      'Footage shows a few individuals break off from a protest to smash City Hall windows. Protesters shout at vandals to stop.  Police then arrive. They arrest multiple individuals near the City Hall windows, including one individual who appeared to approach the vandals in an effort to defuse the situation.  Police fire tear gas and riot rounds at protesters during the arrests. Protesters become agitated.  After police walk arrestee away, protesters continue to shout at police. Police respond with a second bout of tear gas and riot rounds.  A racial slur can be heard shouted, although it is unsure who is shouting.',
    tags: [
      'arrest',
      'less-lethal',
      'projectile',
      'protester',
      'shoot',
      'tear-gas',
    ],
    geolocation: "{'lat': '47.0378741', 'long': '-122.9006951'}",
    title: 'Police respond to broken windows with excessive force',
    date: '2020-05-31',
    date_text: 'May 31st',
    id: 'wa-olympia-1',
    lat: 47.0378741,
    long: -122.9006951,
  },
  {
    state: 'Oregon',
    city: 'Portland',
    desc:
      'Footage shows a few individuals break off from a protest to smash City Hall windows. Protesters shout at vandals to stop.  Police then arrive. They arrest multiple individuals near the City Hall windows, including one individual who appeared to approach the vandals in an effort to defuse the situation.  Police fire tear gas and riot rounds at protesters during the arrests. Protesters become agitated.  After police walk arrestee away, protesters continue to shout at police. Police respond with a second bout of tear gas and riot rounds.  A racial slur can be heard shouted, although it is unsure who is shouting.',
    tags: [
      'arrest',
      'less-lethal',
      'projectile',
      'protester',
      'shoot',
      'tear-gas',
    ],
    geolocation: "{'lat': '47.0378741', 'long': '-122.9006951'}",
    title: 'Police respond to broken windows with excessive force',
    date: '2020-05-31',
    date_text: 'May 31st',
    id: 'wa-olympia-1',
    lat: 47.0378741,
    long: -122.9006951,
  },
  {
    src: ['https://www.youtube.com/watch?v=s7MM1VauRHo'],
    city: 'Portland',
    desc:
      'Footage shows a few individuals break off from a protest to smash City Hall windows. Protesters shout at vandals to stop.  Police then arrive. They arrest multiple individuals near the City Hall windows, including one individual who appeared to approach the vandals in an effort to defuse the situation.  Police fire tear gas and riot rounds at protesters during the arrests. Protesters become agitated.  After police walk arrestee away, protesters continue to shout at police. Police respond with a second bout of tear gas and riot rounds.  A racial slur can be heard shouted, although it is unsure who is shouting.',
    tags: [
      'arrest',
      'less-lethal',
      'projectile',
      'protester',
      'shoot',
      'tear-gas',
    ],
    geolocation: "{'lat': '47.0378741', 'long': '-122.9006951'}",
    title: 'Police respond to broken windows with excessive force',
    date: '2020-05-31',
    date_text: 'May 31st',
    id: 'wa-olympia-1',
    lat: 47.0378741,
    long: -122.9006951,
  },
  {
    src: ['https://www.youtube.com/watch?v=s7MM1VauRHo'],
    state: 'Oregon',
    desc:
      'Footage shows a few individuals break off from a protest to smash City Hall windows. Protesters shout at vandals to stop.  Police then arrive. They arrest multiple individuals near the City Hall windows, including one individual who appeared to approach the vandals in an effort to defuse the situation.  Police fire tear gas and riot rounds at protesters during the arrests. Protesters become agitated.  After police walk arrestee away, protesters continue to shout at police. Police respond with a second bout of tear gas and riot rounds.  A racial slur can be heard shouted, although it is unsure who is shouting.',
    tags: [
      'arrest',
      'less-lethal',
      'projectile',
      'protester',
      'shoot',
      'tear-gas',
    ],
    geolocation: "{'lat': '47.0378741', 'long': '-122.9006951'}",
    title: 'Police respond to broken windows with excessive force',
    date: '2020-05-31',
    date_text: 'May 31st',
    id: 'wa-olympia-1',
    lat: 47.0378741,
    long: -122.9006951,
  },
  {
    src: ['https://www.youtube.com/watch?v=s7MM1VauRHo'],
    state: 'Oregon',
    city: 'Portland',
    tags: [
      'arrest',
      'less-lethal',
      'projectile',
      'protester',
      'shoot',
      'tear-gas',
    ],
    geolocation: "{'lat': '47.0378741', 'long': '-122.9006951'}",
    title: 'Police respond to broken windows with excessive force',
    date: '2020-05-31',
    date_text: 'May 31st',
    id: 'wa-olympia-1',
    lat: 47.0378741,
    long: -122.9006951,
  },
  {
    src: ['https://www.youtube.com/watch?v=s7MM1VauRHo'],
    state: 'Oregon',
    city: 'Portland',
    desc:
      'Footage shows a few individuals break off from a protest to smash City Hall windows. Protesters shout at vandals to stop.  Police then arrive. They arrest multiple individuals near the City Hall windows, including one individual who appeared to approach the vandals in an effort to defuse the situation.  Police fire tear gas and riot rounds at protesters during the arrests. Protesters become agitated.  After police walk arrestee away, protesters continue to shout at police. Police respond with a second bout of tear gas and riot rounds.  A racial slur can be heard shouted, although it is unsure who is shouting.',
    geolocation: "{'lat': '47.0378741', 'long': '-122.9006951'}",
    title: 'Police respond to broken windows with excessive force',
    date: '2020-05-31',
    date_text: 'May 31st',
    id: 'wa-olympia-1',
    lat: 47.0378741,
    long: -122.9006951,
  },
  {
    src: ['https://www.youtube.com/watch?v=s7MM1VauRHo'],
    state: 'Oregon',
    city: 'Portland',
    desc:
      'Footage shows a few individuals break off from a protest to smash City Hall windows. Protesters shout at vandals to stop.  Police then arrive. They arrest multiple individuals near the City Hall windows, including one individual who appeared to approach the vandals in an effort to defuse the situation.  Police fire tear gas and riot rounds at protesters during the arrests. Protesters become agitated.  After police walk arrestee away, protesters continue to shout at police. Police respond with a second bout of tear gas and riot rounds.  A racial slur can be heard shouted, although it is unsure who is shouting.',
    tags: [
      'arrest',
      'less-lethal',
      'projectile',
      'protester',
      'shoot',
      'tear-gas',
    ],
    geolocation: "{'lat': '47.0378741', 'long': '-122.9006951'}",
    date: '2020-05-31',
    date_text: 'May 31st',
    id: 'wa-olympia-1',
    lat: 47.0378741,
    long: -122.9006951,
  },
  {
    src: ['https://www.youtube.com/watch?v=s7MM1VauRHo'],
    state: 'Oregon',
    city: 'Portland',
    desc:
      'Footage shows a few individuals break off from a protest to smash City Hall windows. Protesters shout at vandals to stop.  Police then arrive. They arrest multiple individuals near the City Hall windows, including one individual who appeared to approach the vandals in an effort to defuse the situation.  Police fire tear gas and riot rounds at protesters during the arrests. Protesters become agitated.  After police walk arrestee away, protesters continue to shout at police. Police respond with a second bout of tear gas and riot rounds.  A racial slur can be heard shouted, although it is unsure who is shouting.',
    tags: [
      'arrest',
      'less-lethal',
      'projectile',
      'protester',
      'shoot',
      'tear-gas',
    ],
    geolocation: "{'lat': '47.0378741', 'long': '-122.9006951'}",
    title: 'Police respond to broken windows with excessive force',
    date_text: 'May 31st',
    id: 'wa-olympia-1',
    lat: 47.0378741,
    long: -122.9006951,
  },
  {
    src: ['https://www.youtube.com/watch?v=s7MM1VauRHo'],
    state: 'Oregon',
    city: 'Portland',
    desc:
      'Footage shows a few individuals break off from a protest to smash City Hall windows. Protesters shout at vandals to stop.  Police then arrive. They arrest multiple individuals near the City Hall windows, including one individual who appeared to approach the vandals in an effort to defuse the situation.  Police fire tear gas and riot rounds at protesters during the arrests. Protesters become agitated.  After police walk arrestee away, protesters continue to shout at police. Police respond with a second bout of tear gas and riot rounds.  A racial slur can be heard shouted, although it is unsure who is shouting.',
    tags: [
      'arrest',
      'less-lethal',
      'projectile',
      'protester',
      'shoot',
      'tear-gas',
    ],
    geolocation: "{'lat': '47.0378741', 'long': '-122.9006951'}",
    title: 'Police respond to broken windows with excessive force',
    date: '2020-05-31',
    date_text: 'May 31st',
    id: 'wa-olympia-1',
    long: -122.9006951,
  },
  {
    src: ['https://www.youtube.com/watch?v=s7MM1VauRHo'],
    state: 'Oregon',
    city: 'Portland',
    desc:
      'Footage shows a few individuals break off from a protest to smash City Hall windows. Protesters shout at vandals to stop.  Police then arrive. They arrest multiple individuals near the City Hall windows, including one individual who appeared to approach the vandals in an effort to defuse the situation.  Police fire tear gas and riot rounds at protesters during the arrests. Protesters become agitated.  After police walk arrestee away, protesters continue to shout at police. Police respond with a second bout of tear gas and riot rounds.  A racial slur can be heard shouted, although it is unsure who is shouting.',
    tags: [
      'arrest',
      'less-lethal',
      'projectile',
      'protester',
      'shoot',
      'tear-gas',
    ],
    geolocation: "{'lat': '47.0378741', 'long': '-122.9006951'}",
    title: 'Police respond to broken windows with excessive force',
    date: '2020-05-31',
    date_text: 'May 31st',
    id: 'wa-olympia-1',
    lat: 47.0378741,
  },
  {
    src: [],
    state: '',
    city: '',
    desc: '',
    tags: [],
    geolocation: '',
    title: '',
    date: '',
    date_text: '',
    id: '',
    lat: null,
    long: null,
  },
  {},
];

module.exports = {
  Incidents,
};
