name: build

on: [push, pull_request]

jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: npm install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CI: true
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          OM_API_KEY: ${{ secrets.OM_API_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
          OAUTH_CLIENT: ${{ secrets.OAUTH_CLIENT }}
          TMDB_APIKEY: ${{ secrets.TMDB_APIKEY }}
        with:
          coverageCommand: npm run coverage