export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_LIBRARIES = 'FETCH_LIBRARIES';
export const EDIT_LIBRARY = 'EDIT_LIBRARY';
export const ADD_LIBRARY = 'ADD_LIBRARY';

export const FETCH_HEADMASTER_SCHOOLS = 'FETCH_HEADMASTER_SCHOOLS';
export const FETCH_HEADMASTER_SCHOOL = 'FETCH_HEADMASTER_SCHOOL';
export const EDIT_HEADMASTER_SCHOOL = 'EDIT_HEADMASTER_SCHOOL';

export const FETCH_VILLAGE = 'FETCH_VILLAGE';
export const EDIT_VILLAGE = 'EDIT_VILLAGE';

export const FETCH_HEADMASTER_PROFILE = 'FETCH_HEADMASTER_PROFILE';
export const EDIT_HEADMASTER_PROFILE = 'EDIT_HEADMASTER_PROFILE';
export const FETCH_HEADMASTER_PROFILE_SUCCESS =
  'FETCH_HEADMASTER_PROFILE_SUCCESS';
export const FETCH_HEADMASTER_PROFILE_FAILURE =
  'FETCH_HEADMASTER_PROFILE_FAILURE';

export const FETCH_MENTEE_START = 'FETCH_MENTEE_START';
export const FETCH_MENTEE_SUCCESS = 'FETCH_MENTEE_SUCCESS';
export const FETCH_MENTEE_FAILURE = 'FETCH_MENTEE_FAILURE';
export const EDIT_MENTEE = 'EDIT_MENTEE';

export const FETCH_MENTOR_START = 'FETCH_MENTOR_START';
export const FETCH_MENTOR_SUCCESS = 'FETCH_MENTOR_SUCCESS';
export const FETCH_MENTOR_FAILURE = 'FETCH_MENTOR_FAILURE';
export const EDIT_MENTOR = 'EDIT_MENTOR';
