name: Pull Request to main branch

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: dschep/install-pipenv-action@v1

      - run: make install-dev
        env:
          PIPENV_NOSPIN: 1
