exports.seed = async function(knex) {
    await knex("location").insert([
        {location: 'Unknown', longitude: 2.460415, latitude: 13.531665 },
        {location: 'Lagos, Nigeria', longitude: 3.3941795, latitude:6.4550575,},
        {location: 'Kano, Nigeria', longitude: 8.5364136, latitude: 11.8948389},
        {location: 'Ibadan, Nigeria', longitude: 3.8972497, latitude:7.3777462},
        {location: 'Kaduna, Nigeria', longitude: 7.8533226, latitude: 10.3825318},
        {location: 'Port Harcourt, Nigeria', longitude: 7.0188527, latitude:4.7676576},
        {location: 'Benin, Nigeria', longitude: 5.6221058, latitude: 6.3330586},
        {location: 'Maiduguri, Nigeria' , longitude: 13.1536214, latitude:11.8395375},
        {location: 'Zaria, Nigeri ', longitude: 7.7188449, latitude: 11.1134917 },
        {location: 'Aba, Nigeria' , longitude: 7.364349, latitude: 5.112735},
        {location: 'Ilorin, Nigeria', longitude: 1, latitude:1},
        {location: 'Jos, Nigeria' ,longitude: 1, latitude:1},
        {location: 'Ogbomosho, Nigeria'},
        {location: 'Ovo, Nigeria', longitude: 1, latitude:1 },
        {location: 'Enugu, Nigeria' , longitude: 1, latitude:1},
        {location: 'Abeokuta, Nigeria' , longitude: 1, latitude:1},
        {location: 'Onitsha, Nigeria', longitude: 6.792318, latitude: 6.133234 },
        {location: 'Warri, Nigeria', longitude: 1, latitude:1 },
        {location: 'Sokoto, Nigeria', longitude: 1, latitude:1},
        {location: 'Okene, Nigeria', longitude: 1, latitude:1},
        {location: 'Calabar, Nigeria' , longitude: 1, latitude:1},
        {location: 'Oshogbo, Nigeria', longitude: 1, latitude:1},
        {location: 'Katsina, Nigeria', longitude: 1, latitude:1},
        {location: 'Akure, Nigeria', longitude: 1, latitude:1},
        {location: 'Bobo Dioulasso, Nigeria', longitude: 1, latitude:1},
        {location: 'Ife, Nigeria', longitude: 1, latitude:1},
        {location: 'Bauchi, Nigeria',longitude: 1, latitude:1},
        {location: 'Iseyin, Nigeria',longitude: 1, latitude:1 },
        {location: 'Minna, Nigeria', longitude: 1, latitude:1},
        {location: 'Makurdi, Nigeria', longitude: 1, latitude:1},
        {location: 'Owo, Nigeria', longitude: 1, latitude:1},
        {location: 'Ado, Nigeria',longitude: 1, latitude:1 },
        {location: 'Ilesha, Nigeria',longitude: 1, latitude:1},
        {location: 'Gombe, Nigeria', longitude: 1, latitude:1},
        {location: 'Umuahia, Nigeria', longitude: 1, latitude:1},
        {location: 'Ondo, Nigeria'},
        {location: 'Damaturu, Nigeria'},
        {location: 'Jimeta, Nigeria'},
        {location: 'Ikot Ekpene, Nigeria'},
        {location: 'Gusau, Nigeria'},
        {location: 'Mubi, Nigeria'},
        {location: 'Shagumu, Nigeria'},
        {location: 'Owerri, Nigeria'},
        {location: 'Ugep, Nigeria'},
        {location: 'Ijebu Ode, Nigeria'},
        {location: 'Ise, Nigeria'},
        {location: 'Gboko, Nigeria'},
        {location: 'Ilawe, Nigeria'},
        {location: 'Ikare, Nigeria'},
        {location: 'Abuja, Nigeria'},
        {location: 'Okpoko, Nigeria'},
        {location: 'Awka, Nigeria'},
        {location: 'Sapele, Nigeria'},
        {location: 'Ila, Nigeria'},
        {location: 'Shaki, Nigeria'},
        {location: 'Ijero, Nigeria'},
        {location: 'Otukpo, Nigeria'},
        {location: 'Kishi, Nigeria'},
        {location: 'Bugama, Nigeria'},
        {location: 'Funtua, Nigeria'},
        {location: 'Abakaliki, Nigeria'},
        {location: 'Gbongan, Nigeria'},
        {location: 'Lafia, Nigeria'},
        {location: 'Igboho, Nigeria'},
        {location: 'Amaigbo, Nigeria'},
        {location: 'Gashua, Nigeria'},
        {location: 'Offa, Nigeria'},
        {location: 'Jalingo, Nigeria'},
        {location: 'Bama, Nigeria'},
        {location: 'Uvo, Nigeria'},
        {location: 'Uromi, Nigeria'},
        {location: 'Nsukka, Nigeria'},
        {location: 'Okigwe, Nigeria'},
        {location: 'Modakeke, Nigeria'},
        {location: 'Abidjan, Ivory Coast'},
        {location: 'Bouake, Ivory Coast'},
        {location: 'Daloa, Ivory Coast'},
        {location: 'Yamoussoukro, Ivory Coast'},
        {location: 'Korhogo, Ivory Coast'},
        {location: 'San Pedro, Ivory Coast'},
        {location: 'Divo, Ivory Coast'},
        {location: 'Man, Ivory Coast'},
        {location: 'Gagnoa, Ivory Coast'},
        {location: 'Dakar, Senegal'},
        {location: 'Thies, Senegal'},
        {location: 'Kaolack, Senegal'},
        {location: 'Ziguinchor, Senegal'},
        {location: 'Saint Louis, Senegal'},
        {location: 'Mbour, Senegal'},
        {location: 'Diourbel, Senegal'},
        {location: 'Accra, Ghana'},
        {location: 'Kumasi, Ghana'},
        {location: 'Tamale, Ghana'},
        {location: 'Obuasi, Ghana'},
        {location: 'Conakry, Guinea'},
        {location: 'Kankan, Guinea'},
        {location: 'Bissua, Guinea-Bissau'},
        {location: 'Douala, Cameroon'},
        {location: 'Yaounde, Cameroon'},
        {location: 'Garoua, Cameroon'},
        {location: 'Maroua, Cameroon'},
        {location: 'Bafoussan, Cameroon'},
        {location: 'Ngaoundere, Cameroon'},
        {location: 'Bamenda, Cameroon'},
        {location: 'Kaele, Cameroon'},
        {location: 'Kumba, Cameroon'},
        {location: 'Freetown, Sierra Leone'},
        {location: 'Koidu, Sierra Leone'},
        {location: 'Makeni, Sierra Leone'},
        {location: 'Ouagadougou, Burkina Faso'},
        {location: 'Bobo Diolasso, Burkina Faso'},
        {location: 'Cotonou, Benin'},
        {location: 'Porto Novo, Benin'},
        {location: 'Parakou, Benin'},
        {location: 'Djougou, Benin'},
        {location: 'Bohicon, Benin'},
        {location: 'Kandi, Benin'},
        {location: 'Abomey, Benin'},
        {location: 'Natitingou, Benin'},
        {location: 'Lome, Togo'},
        {location: 'Sokode, Togo'},
        {location: 'Monrovie, Liberia'},
        {location: 'Ajdabivah, Liberia'},
        {location: 'Libreville, Gabon'},
        {location: 'Port Gentil. Gabon'},
        {location: 'Serekunda, Gambia'}
    ])
};
