exports.seed = async function(knex) {
    await knex("tech").insert([
        {name: 'C ++', type: 'Language'},
        {name: 'React', type: 'Framework'},
        {name: 'Nodejs', type: 'Language'},
        {name: 'Angular', type: 'Framework'},
        {name: 'Dev-Ops', type: 'Soft'},
        {name: 'Go!', type: 'Language'},
        {name: 'Ruby', type: 'Language'},
        {name: 'Graphql', type: 'Language'},
        {name: 'JavaScript', type: 'Language'},
        {name: 'Javascript - Front-End', type: 'Soft'},
        {name: 'Javascript - Back-End', type: 'Soft'},
        {name: 'Java', type: 'Language'},
        {name: 'Kotlin', type: 'Language'},
        {name: 'C#', type: 'Language'},
        {name: 'Rest API', type: 'Soft'},
        {name: 'Swift', type: 'Language'},
        {name: 'Ember', type: 'Framework'},
        {name: 'AWS', type: 'Soft'},
        {name: 'SQL', type: 'Language'},
        {name: '.NEt', type: 'Language'},
        {name: 'TypeScript', type: 'Language'},
        {name: 'Linux', type: 'Soft'},
        {name: 'HTML', type: 'Language'},
        {name: 'Docker', type: 'Soft'},
        {name: 'PHP', type: 'Language'},
        {name: 'Perl', type: 'Language'},
        {name: 'Python', type: 'Language'},
        {name: 'PowerShell', type: 'Soft'},
        {name: 'Rust', type: 'Language'},
        {name: 'Unix', type: 'Soft'},
        {name: 'Visual Basic', type: 'Language'},
        {name: 'Vim', type: 'Soft'},
        {name: 'MATLAB', type: 'Language'},
        {name: 'Functional Programming', type: 'Soft'},
        {name: 'Object Oriented Programming', type: 'Soft'},
        {name: 'Interviewing', type: 'Soft'},
        {name: 'Communication', type: 'Soft'},
        {name: 'Agile',type: 'Soft'},
        {name: 'Leadership',type: 'Soft'},
        {name: 'Integrated Development Environment', type: 'Soft'},
        {name: 'NPM', type: 'Soft'},
        {name: 'Express', type: 'Framework'},
        {name: 'Rails', type: 'Framework'},
        {name: 'Django', type: 'Framework'},
        {name: 'Vue', type: 'Framework'},
        {name: 'Graphql-Apollo', type: 'Framework'},
        {name: 'Graphql-Yoga', type: 'Framework'},
        {name: 'Spring', type: 'Framework'},
        {name: 'Laravel Lumen',type: 'Framework'},
        {name: 'Flask', type: 'Framework'},
        {name: 'ASP.NET', type: 'Framework'},
        {name: 'DRY Code', type: 'Soft'},
        {name: 'Machine Learning', type: 'Soft'},
    ])
};
