# .codeclimate.yml
version: "2"
checks:
  # Disable checks for similar code.
  # Because this creates too many false positives.
  similar-code:
    enabled: false
  # Increase the number of lines allowed for a method.
  # Because this is more reasonable for JavaScript.
  method-lines:
    config:
      threshold: 50
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
plugins: 
  eslint:
    enabled: true
    channel: "eslint-6"  