require('dotenv').config();
const bcrypt = require('bcryptjs');

const hashJane = bcrypt.hashSync(process.env.USER1, 10)
const hashLucy = bcrypt.hashSync(process.env.USER2, 10)
const hashZac = bcrypt.hashSync(process.env.USER3, 10);

exports.seed = function(knex) {
    return knex('mentor').del()
      .then(function () {
        return knex('mentor').insert([
          {id: 1, first_name: 'Jane', last_name: 'Doe', city: 'Queens', state: 'New York', email: 'janedoe@email.com', password: hashJane, profession: 'UX Designer', image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Jane Doe. I\'m a UX Designer from New York, and have been in the industry for over 6 years. I specialize in Graphic Design and am passionate about sharing everything that I \'ve learned on my journey over the last 6 years. Ultimately, my goal is to help teach you everything about designing.'},
          {id: 2, first_name: 'Lucy', last_name: 'Lee', city: 'Atlanta', state: 'Georgia', email: 'lucylee@gmail.com', password: hashLucy, profession: 'Graphic Designer', image: 'https://images.unsplash.com/photo-1541779408-c355f91b42c9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Lucy Lee. I\'m a Grapic Designer from Atlanta, and have been in the industry for over 7 years. I specialize in Graphic Design and am passionate about sharing everything that I \'ve learned on my journey over the last 7 years. Ultimately, my goal is to help teach you everything about designing.'},
          {id: 3, first_name: 'Zac', last_name: 'Burns', city: 'Bronx', state: 'New York', email: 'zacburns@email.com', password: hashZac, profession: 'UX Designer', image: 'https://images.unsplash.com/photo-1525748822304-6807cb1348ab?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Zach Burns. I\'m a UX Designer from New York, and have been in the industry for over 12 years. I specialize in Graphic Design and am passionate about sharing everything that I \'ve learned on my journey over the last 12 years. Ultimately, my goal is to help teach you everything about designing.'},
          {id: 4, first_name: 'Kendra', last_name: 'Morrison', city: 'Chesapeake', state: 'Virginia', email: 'kendramorrison@email.coml', password: 'kendramorrison', profession: 'Paramedic', image: 'https://images.unsplash.com/photo-1592063405621-50770da2eca0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Kendra Morrison. I\'m a Paramedic from Virginia, and have been in the industry for over 6 years. I am passionate about sharing everything that I \'ve learned on my journey.Ultimately, my goal is to help teach you everything about the field.'},
          {id: 5, first_name: 'Kerri', last_name: 'Sparrow', city: 'Minneapolis', state: 'Minnesota', email: 'kerrisparrow@email.com', password: 'kerrisparrow', profession: 'Epidemiologist', image: 'https://images.unsplash.com/photo-1592063405852-707f0ce83e34?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is . I\'m a Paramedic from Virginia, and have been in the industry for over 6 years. I am passionate about sharing everything that I \'ve learned on my journey.Ultimately, my goal is to help teach you everything about the field.'},
          {id: 6, first_name: 'Ruby', last_name: 'Bates', city: 'Fort Worth', state: 'Texas', email: 'rubybates@email.com', password: 'rubybates', profession: 'Childcare Worker', image: 'https://images.unsplash.com/photo-1592085552145-5e508372c3f4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is . I\'m a Childcare Worker from Texas, and have been in the industry for over 4 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field.'}, 
          {id: 7, first_name: 'Hoorain', last_name: 'Lawrence', city: 'New Orleans', state: 'Louisana', email: 'hoorainlawrence@email.com', password: 'hoorainlawrence', profession: 'Social Worker', image: 'https://images.unsplash.com/photo-1591364402267-2af94c1fdcd6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Hoorain Lawrence. I\'m a Social Worker from Louisana, and have been in the industry for over 9 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field.'},
          {id: 8, first_name: 'Dani', last_name: 'Middleton', city: 'Chandler', state: 'Arizona', email: 'danimiddleton@email.com', password: 'danimiddleton', profession: 'Logistician', image: 'https://images.unsplash.com/photo-1591641079593-983f261d24e3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Dani Middleton . I\'m a Logistician from Arizona, and have been in the industry for over 3 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field.'},
          {id: 9, first_name: 'Sofie', last_name: 'Finnegan', city: 'Honolulu', state: 'Hawaii', email: 'sofiefinnegan@email.com', password: 'sofiefinnegan', profession: 'Radiologic Technologist', image: 'https://images.unsplash.com/photo-1560775988-04f219657f08?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Sofie Finnegan . I\'m a Radiologic Technologist from Hawaii, and have been in the industry for over 3 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field'},
          {id: 10, first_name: 'Nicola', last_name: 'Vaughan', city: 'Chicago', state: 'Illnois', email: 'nicolavaughan@email.com', password: 'nicolavaughan', profession: 'Preschool Teacher', image: 'https://images.unsplash.com/photo-1590952894196-e3ef8468de0b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Nicola Vaughan . I\'m a Preschool Teacher from Chicago, and have been in the industry for over 4 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field'},
          {id: 11, first_name: 'Nyah', last_name: 'Cain', city: 'Charlotte', state: 'North Carolina', email: 'nyahcain@email.com', password: 'nyahcain', profession: 'Paralegal', image: 'https://images.unsplash.com/photo-1589279715734-6631a314dfa2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Nyah Cain . I\'m a Paralegal from Charlotte, and have been in the industry for over 3 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field'},
          {id: 12, first_name: 'Camron', last_name: 'Bautista', city: 'Birmingham', state: 'Alabama', email: 'camronbautista@email.com', password: 'camronbautista', profession: 'Dentist', image: 'https://images.unsplash.com/photo-1583264277168-58ceba4b84e7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Camron Bautista . I\'m a Dentist from Alabama, and have been in the industry for over 5 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field'},
          {id: 13, first_name: 'Angela', last_name: 'Hook', city: 'Huntington', state: 'New York', email: 'angelahook@email.com', password: 'angelahook', profession: 'Photographer', image: 'https://images.unsplash.com/photo-1590567219915-121024b10645?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Angela Hook . I\'m a Photographer from New York, and have been in the industry for over 9 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field'},
          {id: 14, first_name: 'Ivie', last_name: 'Stephens', city: 'Buffalo', state: 'New York', email: 'iviestephans@email.com', password: 'iviestephans', profession: 'UX Designer', image: 'https://images.unsplash.com/photo-1590565536586-70a2fac75599?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Ivie Stephans . I\'m a UX Designer from New York, and have been in the industry for over 3 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field'}, 
          {id: 15, first_name: 'Myla', last_name: 'Dickinson', city: 'Chula Vista', state: 'California', email: 'myladickinson@email.com', password: 'myladickinson', profession: 'Graphic Designer', image: 'https://images.unsplash.com/photo-1590087950153-9061df8c9126?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Myla Dickinson . I\'m a Graphic Designer from California, and have been in the industry for over 3 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field'},
          {id: 16, first_name: 'Pascal', last_name: 'Dawson', city: 'Philadelphia', state: 'Pennsylvania', email: 'pascaldawson@email.com', password: 'pascaldawson', profession: 'Software Engineer', image: 'https://images.unsplash.com/photo-1519058082700-08a0b56da9b4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Pascal Dawson . I\'m a Software Engineer, and have been in the industry for over 3 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field'},
          {id: 17, first_name: 'Kirk', last_name: 'Greenaway', city: 'Baltimore', state: 'Maryland', email: 'kirkgreenway@email.com', password: 'kirkgreenway', profession: 'Paralegal', image: 'https://images.unsplash.com/photo-1524383880260-db51af30f5e6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Kirk Greenway. I\'m a Paralegal from Baltimore, and have been in the industry for over 3 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field'},
          {id: 18, first_name: 'Will', last_name: 'Cross', city: 'Miami', state: 'Florida', email: 'willcross@email.com', password: 'willcross', profession: 'Teacher', image: 'https://images.unsplash.com/photo-1507038732509-8b1a9623223a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Will Cross . I\'m a Teacher from Miami, and have been in the industry for over 3 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field'},
          {id: 19, first_name: 'Hollie', last_name: 'Ellis', city: 'Sacramento', state: 'California', email: 'hollieellis@email.com', password: 'hollieellis', profession: 'UX Designer', image: 'https://images.unsplash.com/photo-1556630820-200f321dce4a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Hollie Ellis . I\'m a UX Designer from California, and have been in the industry for over 3 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field'},
          {id: 20, first_name: 'Clark', last_name: 'Russell', city: 'Raleigh', state: 'North Carolina', email: 'clarkrussell@email.com', password: 'clarkrussell', profession: 'Software Engineer', image: 'https://images.unsplash.com/photo-1566802842272-e694af42eb29?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=60', description: 'Hello, my name is Clark Russell . I\'m a Software Engineer from North Carolina, and have been in the industry for over 3 years. I am passionate about sharing everything that I \'ve learned on my journey. Ultimately, my goal is to help teach you everything about the field'},
          // {id: 12, first_name: '', last_name: '', city: '', state: '', email: '', password: '', profession: '', image: '', description: ''},
          // {id: 13, first_name: '', last_name: '', city: '', state: '', email: '', password: '', profession: '', image: '', description: ''},
          // {id: 14, first_name: '', last_name: '', city: '', state: '', email: '', password: '', profession: '', image: '', description: ''}, 
          // {id: 15, first_name: '', last_name: '', city: '', state: '', email: '', password: '', profession: '', image: '', description: ''},
          // {id: 16, first_name: '', last_name: '', city: '', state: '', email: '', password: '', profession: '', image: '', description: ''},
          // {id: 17, first_name: '', last_name: '', city: '', state: '', email: '', password: '', profession: '', image: '', description: ''},
          // {id: 18, first_name: '', last_name: '', city: '', state: '', email: '', password: '', profession: '', image: '', description: ''},
          // {id: 19, first_name: '', last_name: '', city: '', state: '', email: '', password: '', profession: '', image: '', description: ''},
          // {id: 20, first_name: '', last_name: '', city: '', state: '', email: '', password: '', profession: '', image: '', description: ''},

        ]);
      });
  };
  