name: build

on: [push, pull_request]

jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - run: npm install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
          FIREBASE_TYPE: ${{ secrets.FirebaseType }}
          FIREBASE_PROJECT_ID: ${{ secrets.FirebaseProjectId }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FirebasePrivateKeyId }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FirebasePrivateKey }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FirebaseClientEmail }}
          FIREBASE_CLIENT_ID: ${{ secrets.FirebaseClientId }}
          FIREBASE_AUTH_URI: ${{ secrets.FirebaseAuthUri }}
          FIREBASE_TOKEN_URI: ${{ secrets.FirebaseTokenUri }}
          FIREBASE_AUTH_CERT_URL: ${{ secrets.AuthCertUrl }}
          FIREBASE_CLIENT_CERT_URL: ${{ secrets.ClientCertUrl }}
        with:
          coverageCommand: npm run coverage
          debug: true
