exclude_patterns:
- "database/seeds/001players.js"
- "database/seeds/002players.js"
- "database/seeds/003players.js"
- "database/seeds/004players.js"
- "database/seeds/005players.js"
- "database/seeds/006players.js"
- "database/seeds/007players.js"
- "database/seeds/008players.js"
- "database/seeds/009players.js"
- "database/seeds/010Players.js"
- "database/seeds/011players.js"
- "database/seeds/012players.js"
- "database/seeds/013players.js"
- "database/seeds/014players.js"
- "database/seeds/015players.js"
- "database/seeds/016players.js"
- "database/migrations/20200413224226_players.js"
- "database/migrations/20200410222338_fans.js"
- "middleware/verify-players.js"